version: '3.6'
services:
  mockoon:
    image: mockoon/cli:latest
    command: ["--data", "data", "--port", "3000"]
    networks:
      backend:
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
    - ./tests/mock/nhl_mock.json:/data:readonly
  postgres:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=password"
      - "PGPASSWORD=password"
    ports:
    - "127.0.0.1:5432:5432"
    restart: always
    networks:
      - backend
    volumes:
    - db_data_test:/var/lib/postgresql/data
    - ./infrastructure/database/init.sql:/docker-entrypoint-initdb.d/bootstrap-tracking.sql
  migration:
    image: flyway/flyway
    environment:
      - "FLYWAY_URL=jdbc:postgresql://postgres:5432/tracking"
      - "FLYWAY_USER=postgres"
      - "FLYWAY_PASSWORD=password"
      - "FLYWAY_SCHEMAS=tracking"
    command: -connectRetries=60 migrate
    volumes:
      - $PWD/infrastructure/database/migrations:/flyway/sql
    depends_on:
      - postgres
    networks:
      - backend
networks:
  frontend:
  backend:
volumes:
  db_data_test: