version: '3.6'
services:
  postgres:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=password"
      - "PGPASSWORD=password"
    ports:
    - "127.0.0.1:5432:5432"
    restart: always
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./infrastructure/database/init.sql:/docker-entrypoint-initdb.d/bootstrap-tracking.sql
  migration:
    image: flyway/flyway
    environment:
      - "FLYWAY_URL=jdbc:postgresql://postgres:5432/tracking"
      - "FLYWAY_USER=postgres"
      - "FLYWAY_PASSWORD=password"
      - "FLYWAY_SCHEMAS=tracking"
    command: -connectRetries=60 migrate
    volumes:
      - $PWD/infrastructure/database/migrations:/flyway/sql
    depends_on:
      - postgres
    networks:
      - backend
  bspn-api:
    build:
      context: .
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USERNAME=postgres"
      - "POSTGRES_HOST=postgres"
      - "POSTGRES_PORT=5432"
      - "POSTGRES_DATABASE=tracking"
    ports:
    - "127.0.0.1:8020:8020"
    networks:
      - backend
    depends_on:
      - postgres
  graphql-engine:
    image: hasura/graphql-engine:v2.25.0
    ports:
    - "127.0.0.1:8080:8080"
    depends_on:
    - "postgres"
    - "migration"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/tracking
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - backend
networks:
  frontend:
  backend:
volumes:
  db_data: